from pathlib import Path

root = Path('/home/ubuntu/package-earn-pro')

routers = root / 'server/routers.ts'
s = routers.read_text()
s = s.replace('''      if (input.referralCode) {\n        const referrer = await db.select().from(profiles).where(eq(profiles.referralCode, input.referralCode.toUpperCase())).limit(1);\n        if (!referrer[0]) fail("Referral code was not found.");\n        referredByUserId = referrer[0].userId;\n      }''', '''      if (input.referralCode) {\n        const referralValue = input.referralCode.trim();\n        let referrer = (await db.select().from(profiles).where(eq(profiles.referralCode, referralValue.toUpperCase())).limit(1))[0];\n        if (!referrer) referrer = (await db.select().from(profiles).where(eq(profiles.username, referralValue.toLowerCase())).limit(1))[0];\n        if (!referrer) fail("Referral code or username was not found.");\n        referredByUserId = referrer.userId;\n      }''')
s = s.replace('''        const referrer = await db.select().from(profiles).where(eq(profiles.referralCode, input.referralCode.toUpperCase())).limit(1);\n        if (!referrer[0]) fail("Referral code was not found.");\n        if (referrer[0].userId === user.id) fail("You cannot use your own referral code.");\n        referredByUserId = referrer[0].userId;''', '''        const referralValue = input.referralCode.trim();\n        let referrer = (await db.select().from(profiles).where(eq(profiles.referralCode, referralValue.toUpperCase())).limit(1))[0];\n        if (!referrer) referrer = (await db.select().from(profiles).where(eq(profiles.username, referralValue.toLowerCase())).limit(1))[0];\n        if (!referrer) fail("Referral code or username was not found.");\n        if (referrer.userId === user.id) fail("You cannot use your own referral code.");\n        referredByUserId = referrer.userId;''')
s = s.replace('''      return { referralCode: profile.referralCode, totalReferrals: referrals.length, purchasedReferrals: purchasers.size, withdrawalLimitPkr: profile.withdrawalLimitPkr, referrals };''', '''      return { username: profile.username, referralCode: profile.referralCode, totalReferrals: referrals.length, purchasedReferrals: purchasers.size, withdrawalLimitPkr: profile.withdrawalLimitPkr, referrals };''')
routers.write_text(s)

home = root / 'client/src/pages/Home.tsx'
h = home.read_text()
h = h.replace('  ArrowDownToLine, ArrowUpRight, BadgeCheck, Bell, Boxes, CircleHelp, ClipboardList,\n  Copy, CreditCard, Gem, Gift, History, Home as HomeIcon, Landmark, LayoutDashboard,\n  Loader2, LogOut, Menu, PackageCheck, PiggyBank, Play, Plus, Send, Settings2,\n  ShieldCheck, Sparkles, Users, WalletCards, X,', '  ArrowDownToLine, ArrowUpRight, BadgeCheck, Bell, Boxes, CircleHelp, ClipboardList,\n  Copy, CreditCard, Eye, EyeOff, Gem, Gift, History, Home as HomeIcon, Landmark, LayoutDashboard,\n  Loader2, LogOut, Menu, PackageCheck, PiggyBank, Play, Plus, Send, Settings2,\n  ShieldCheck, Sparkles, Users, WalletCards, X,')
h = h.replace('type Page = "dashboard" | "packages" | "wallet" | "deposit" | "withdrawal" | "earn" | "history" | "referral" | "support" | "admin";', 'type Page = "dashboard" | "packages" | "wallet" | "deposit" | "withdrawal" | "earn" | "history" | "referral" | "support" | "profile" | "admin";')
h = h.replace('''          <div className="flex items-center gap-2"><LanguageToggle language={language} onChange={setLanguage} /><button aria-label="Open navigation" onClick={() => setMobileNavOpen(true)} className="grid size-9 place-items-center rounded-xl border border-white/10 bg-white/5 text-slate-200 lg:hidden"><Menu className="size-4" /></button><button onClick={() => selectPage("wallet")} className="hidden items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-bold text-emerald-200 md:flex"><WalletCards className="size-4" />{money(profile.balancePkr)}</button></div>''', '''          <div className="flex items-center gap-2"><LanguageToggle language={language} onChange={setLanguage} /><button aria-label={t("profile")} onClick={() => selectPage("profile")} className="grid size-9 place-items-center rounded-xl border border-white/10 bg-white/5 text-slate-200"><Settings2 className="size-4" /></button><button aria-label="Open navigation" onClick={() => setMobileNavOpen(true)} className="grid size-9 place-items-center rounded-xl border border-white/10 bg-white/5 text-slate-200 lg:hidden"><Menu className="size-4" /></button><button onClick={() => selectPage("wallet")} className="hidden items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-bold text-emerald-200 md:flex"><WalletCards className="size-4" />{money(profile.balancePkr)}</button></div>''')
h = h.replace('''          {needsProfile ? <ProfileSetup profile={profile} t={t} onDone={invalidateCore} /> : <Workspace page={page} setPage={selectPage} t={t} language={language} profile={profile} overview={overview.data} overviewLoading={overview.isLoading} packages={publicData.data?.packages ?? []} settings={publicData.data?.settings} announcements={announcements.data ?? []} wallet={wallet.data} invalidateCore={invalidateCore} />}''', '''          {needsProfile ? <ProfileSetup profile={profile} t={t} onDone={invalidateCore} /> : <Workspace page={page} setPage={selectPage} t={t} language={language} user={user} profile={profile} overview={overview.data} overviewLoading={overview.isLoading} packages={publicData.data?.packages ?? []} settings={publicData.data?.settings} announcements={announcements.data ?? []} wallet={wallet.data} invalidateCore={invalidateCore} />}''')
h = h.replace('''function Workspace({ page, setPage, t, language, profile, overview, overviewLoading, packages, settings, announcements, wallet, invalidateCore }: any) {\n  if (overviewLoading || !overview) return <LoadingScreen text={t("loading")} />;\n  const content: Record<Page, ReactNode> = { dashboard: <Dashboard t={t} overview={overview} announcements={announcements} setPage={setPage} />, packages: <Packages t={t} plans={packages} balance={profile.balancePkr} active={overview.activePackage} onDone={invalidateCore} />, wallet: <Wallet t={t} wallet={wallet} setPage={setPage} />, deposit: <Deposit t={t} settings={settings} onDone={invalidateCore} />, withdrawal: <Withdrawal t={t} profile={profile} settings={settings} onDone={invalidateCore} />, earn: <Earn t={t} overview={overview} onDone={invalidateCore} />, history: <TransactionHistory t={t} />, referral: <Referral t={t} />, support: <Support t={t} />, admin: <AdminPanel t={t} /> };\n  return <>{content[page as Page]}<p className="mt-8 text-center text-[11px] text-slate-500">{t("brand")} · {language === "ur" ? "محفوظ ورک اسپیس" : "Secure member workspace"}</p></>;\n}''', '''function Workspace({ page, setPage, t, language, user, profile, overview, overviewLoading, packages, settings, announcements, wallet, invalidateCore }: any) {\n  if (overviewLoading || !overview) return <LoadingScreen text={t("loading")} />;\n  const content: Record<Page, ReactNode> = { dashboard: <Dashboard t={t} overview={overview} announcements={announcements} setPage={setPage} />, packages: <Packages t={t} plans={packages} balance={profile.balancePkr} active={overview.activePackage} onDone={invalidateCore} />, wallet: <Wallet t={t} wallet={wallet} setPage={setPage} />, deposit: <Deposit t={t} settings={settings} onDone={invalidateCore} />, withdrawal: <Withdrawal t={t} profile={profile} settings={settings} onDone={invalidateCore} />, earn: <Earn t={t} overview={overview} onDone={invalidateCore} />, history: <TransactionHistory t={t} />, referral: <Referral t={t} />, support: <Support t={t} />, profile: <ProfilePage t={t} user={user} profile={profile} activePackage={overview.activePackage} totalEarnedPkr={overview.totalEarnedPkr} />, admin: <AdminPanel t={t} /> };\n  return <><WhatsAppBanner t={t} joined={Boolean(profile.whatsappJoined)} onJoin={async () => { window.open("https://whatsapp.com/channel/0029VbDB4LpDZ4LhbhGZsJ10", "_blank", "noopener,noreferrer"); await invalidateCore(); }} /><div className="mt-4">{content[page as Page]}</div><p className="mt-8 text-center text-[11px] text-slate-500">{t("brand")} · {language === "ur" ? "محفوظ ورک اسپیس" : "Secure member workspace"}</p></>;\n}''')
# Fix the profile currency label and referral link.
h = h.replace('<option value="USD">USD / USDT</option>', '<option value="USD">USD (PayPal)</option>')
h = h.replace('const link = `${window.location.origin}/?ref=${referral.data.referralCode}`;', 'const link = `${window.location.origin}/?ref=${encodeURIComponent(referral.data.username)}`;')
# Deposit helper and client-side range.
h = h.replace('<span className="field-label">{t("amount")} ({currency})</span><input className="field" type="number" min="1" step="0.01" value={amount}', '<span className="field-label">{t("amount")} ({currency})</span><input className="field" type="number" min={currency === "PKR" ? "100" : "0.36"} max={currency === "PKR" ? "1000" : "3.57"} step="0.01" value={amount}')
h = h.replace('<label><span className="field-label">{t("amount")} ({currency})</span><input className="field" type="number" min={currency === "PKR" ? "100" : "0.36"} max={currency === "PKR" ? "1000" : "3.57"} step="0.01" value={amount}', '<label><span className="field-label">{t("amount")} ({currency})</span><input className="field" type="number" min={currency === "PKR" ? "100" : "0.36"} max={currency === "PKR" ? "1000" : "3.57"} step="0.01" value={amount}')
# Ensure deposit helper is visible in the existing form.
h = h.replace('<div className="panel"><form onSubmit={(event) => { event.preventDefault(); if (!proof)', '<div className="panel"><form onSubmit={(event) => { event.preventDefault(); if (!proof)')
h = h.replace('<label><span className="field-label">{t("paymentMethod")}</span>', '<p className="mb-4 rounded-xl border border-amber-300/15 bg-amber-300/10 p-3 text-xs text-amber-100">{t("depositLimit")}</p><label><span className="field-label">{t("paymentMethod")}</span>', 1)
# Withdrawal helper, USD limits, and PayPal label.
h = h.replace('<p className="mt-6 rounded-xl border border-amber-300/15 bg-amber-300/10 p-3 text-xs leading-5 text-amber-100/80">PKR {settings.minimumWithdrawalPkr} – PKR {settings.maximumWithdrawalPkr}</p>', '<p className="mt-6 rounded-xl border border-amber-300/15 bg-amber-300/10 p-3 text-xs leading-5 text-amber-100/80">{t("withdrawLimit")}<br />{t("withdrawLimitUsd")}</p>{profile.withdrawalLimitPkr < 50 && <p className="mt-3 rounded-xl border border-red-300/20 bg-red-300/10 p-3 text-xs leading-5 text-red-100">{t("inviteUnlock")}</p>}{profile.withdrawalLimitPkr >= 50 && <p className="mt-3 rounded-xl border border-emerald-300/20 bg-emerald-300/10 p-3 text-xs leading-5 text-emerald-100">{t("withdrawalUnlocked")}</p>}')
h = h.replace('<input className="field" type="number" min="1" step="0.01" value={amount}', '<input className="field" type="number" min={currency === "PKR" ? "50" : "0.18"} max={currency === "PKR" ? "3000" : "10.71"} step="0.01" value={amount}', 1)
h = h.replace('<label><span className="field-label">{t("accountDetails")}</span>', '<label><span className="field-label">{currency === "USD" ? t("payPalEmail") : t("accountDetails")}</span>')
# Add dashboard WhatsApp card before announcements.
needle = '</div>{announcements.length > 0 && <div className="panel mt-5">'
replacement = '</div><WhatsAppCard t={t} joined={Boolean(overview.profile.whatsappJoined)} onJoin={async () => { window.open("https://whatsapp.com/channel/0029VbDB4LpDZ4LhbhGZsJ10", "_blank", "noopener,noreferrer"); }} />{announcements.length > 0 && <div className="panel mt-5">'
h = h.replace(needle, replacement, 1)
# Append compact components before ProfileSetup.
marker = 'function ProfileSetup({ profile, t, onDone }: { profile: { username: string; preferredCurrency: "PKR" | "USD" }; t: (key: TranslationKey) => string; onDone: () => void }) {'
insert = '''function WhatsAppBanner({ t, joined, onJoin }: any) { return <div className="flex items-center justify-between gap-3 rounded-2xl border border-emerald-300/20 bg-emerald-300/10 px-4 py-3 text-sm"><span className="font-semibold text-emerald-100">{joined ? t("whatsappBonus") : t("whatsappBanner")}</span>{!joined && <button onClick={onJoin} className="rounded-lg bg-amber-300 px-3 py-2 text-xs font-bold text-slate-950">{t("joinNow")}</button>}</div>; }\nfunction WhatsAppCard({ t, joined, onJoin }: any) { return <div className="panel mt-5 border-emerald-300/20"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">{t("whatsappTitle")}</p><p className="mt-1 text-sm text-slate-300">{t("whatsappSubtitle")}</p></div>{joined ? <span className="rounded-xl bg-emerald-400/15 px-3 py-2 text-xs font-bold text-emerald-200">{t("whatsappBonus")}</span> : <button onClick={onJoin} className="rounded-xl bg-amber-300 px-4 py-2 text-sm font-bold text-slate-950">{t("joinNow")}</button>}</div></div>; }\nfunction ProfilePage({ t, user, profile, activePackage, totalEarnedPkr }: any) { const [showPassword, setShowPassword] = useState(false); const referral = trpc.referral.get.useQuery(); return <><PageHeading eyebrow={t("profile")} title={t("profile")} description={t("profileEmail")} /><div className="grid gap-5 md:grid-cols-2"><div className="panel space-y-4"><div><p className="field-label">{t("profileEmail")}</p><p className="mt-1 font-semibold">{user?.email ?? "—"}</p></div><div><p className="field-label">{t("profileUsername")}</p><p className="mt-1 font-semibold">{profile.username}</p></div><div><p className="field-label">{t("profilePassword")}</p><div className="mt-1 flex items-center justify-between rounded-xl border border-white/10 bg-slate-950/20 px-3 py-2 text-sm"><span>{showPassword ? t("passwordSaved") : "••••••••"}</span><button type="button" aria-label={showPassword ? t("hidePassword") : t("showPassword")} onClick={() => setShowPassword(!showPassword)} className="text-amber-300">{showPassword ? <EyeOff className="size-4" /> : <Eye className="size-4" />}</button></div></div></div><div className="panel space-y-4"><div><p className="field-label">{t("activePackage")}</p><p className="mt-1 font-semibold">{activePackage ? `${activePackage.icon} ${activePackage.name}` : t("noActivePackageProfile")}</p></div><div><p className="field-label">{t("totalReferrals")}</p><p className="mt-1 text-2xl font-bold">{referral.data?.totalReferrals ?? 0}</p></div><div><p className="field-label">{t("totalEarnings")}</p><p className="mt-1 text-2xl font-bold text-amber-300">{money(totalEarnedPkr)}</p></div></div></div></>; }\n\n'''
h = h.replace(marker, insert + marker)
home.write_text(h)

admin = root / 'client/src/components/AdminPanel.tsx'
a = admin.read_text().replace('<option value="USD">USD / USDT</option>', '<option value="USD">USD (PayPal)</option>')
admin.write_text(a)
